[pytest]
testpaths        = .
python_files     = test_*.py
python_classes   = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --capture=no
    --show-capture=all
    -p no:warnings

log_cli            = true
log_cli_level      = INFO
log_cli_format     = %(asctime)s [%(levelname)s] %(name)s -- %(message)s
log_cli_date_format= %H:%M:%S
log_file           = reports/selenium_test_execution.log
log_file_level     = DEBUG
log_file_format    = %(asctime)s [%(levelname)-8s] %(name)s -- %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S

timeout = 180
