name: Deploy Mobile App
run-name: Deploy Mobile App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_mobile:
    name: Build & Deploy Mobile App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter APK
        run: flutter build apk --release --no-pub
