name: Deploy Web App
run-name: Deploy Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_web:
    name: Build & Deploy Web App to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        continue-on-error: true
        run: flutter build web --release

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        continue-on-error: true
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: true
